apiVersion: harness.io/v1
kind: Resource
name: test_push3
identifier: test_push3
type: database
owner: group:account/Foster_Clark
spec:
  lifecycle: production
  dependsOn:\n    - component:account/relationtest
  providesApis:\n    - api:account/philly-special-api\n    - api:account/api1

  partOf:\n    - system:account/AAtest1
metadata:
  description: Testing this stuff to see if it works
  tags:\n    - tag1\n    - tag2\n    - tag3

