apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test123Foster
  description: test123
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: foster.clark@harness.io
  lifecycle: experimental
